
// This file is automaticaly generated by 'toybox'
export const navs: I18nNavMenu = {
  "ja": [
    {
      "category": "会社概要",
      "root": "/about/toc",
      "items": [
        {
          "caption": "会社情報",
          "link": "/about/information",
          "items": []
        },
        {
          "caption": "経営理念・社是",
          "link": "/about/philosophy",
          "items": []
        },
        {
          "caption": "社長あいさつ",
          "link": "/about/message",
          "items": []
        },
        {
          "caption": "プライバシーポリシー",
          "link": "/about/privacy",
          "items": []
        },
        {
          "caption": "採用・募集",
          "link": "/about/recruit",
          "items": []
        }
      ]
    },
    {
      "category": "翻訳・通訳",
      "root": "/lang/toc",
      "items": [
        {
          "caption": "翻訳",
          "link": "/lang/translation",
          "items": []
        },
        {
          "caption": "通訳",
          "link": "/lang/interpretation",
          "items": []
        },
        {
          "caption": "オンライン通訳",
          "link": "/lang/online",
          "items": []
        },
        {
          "caption": "機械翻訳",
          "link": "/lang/mt",
          "items": []
        },
        {
          "caption": "翻訳・通訳実績一覧",
          "link": "/lang/works",
          "items": []
        }
      ]
    },
    {
      "category": "EC",
      "root": "/ec/ec",
      "items": [
        {
          "caption": "Online Shop",
          "link": "/ec/ec",
          "items": []
        }
      ]
    },
    {
      "category": "IT事業",
      "root": "/it/toc",
      "items": [
        {
          "caption": "翻訳支援ツール",
          "link": "/it/cat",
          "items": []
        },
        {
          "caption": "自然言語処理",
          "link": "/it/nlp",
          "items": []
        },
        {
          "caption": "DX・テレワーク",
          "link": "/it/dx",
          "items": []
        }
      ]
    },
    {
      "category": "その他",
      "root": "/others/toc",
      "items": [
        {
          "caption": "編集・DTP",
          "link": "/others/edit",
          "items": []
        },
        {
          "caption": "インバウンド交流事業",
          "link": "/others/inbound",
          "items": []
        },
        {
          "caption": "語学研修",
          "link": "/others/train",
          "items": []
        },
        {
          "caption": "著作権登録",
          "link": "/others/copyright",
          "items": []
        }
      ]
    }
  ],
  "zh": [
    {
      "category": "ABOUT",
      "root": "/about/toc",
      "items": []
    },
    {
      "category": "LANG",
      "root": "/lang/toc",
      "items": []
    },
    {
      "category": "IT",
      "root": "/it/toc",
      "items": []
    },
    {
      "category": "OTHERS",
      "root": "/others/toc",
      "items": []
    }
  ],
  "en": [
    {
      "category": "ABOUT",
      "root": "/about/toc",
      "items": [
        {
          "caption": "Company information",
          "link": "/about/information",
          "items": []
        }
      ]
    },
    {
      "category": "LANG",
      "root": "/lang/toc",
      "items": []
    },
    {
      "category": "IT",
      "root": "/it/toc",
      "items": []
    },
    {
      "category": "OTHERS",
      "root": "/others/toc",
      "items": []
    }
  ]
}
export const pagedirs: StaticDir[] = [
  {
    "params": {
      "dirs": "about"
    },
    "props": {
      "lang": "ja",
      "layout": "TOC"
    }
  },
  {
    "params": {
      "dirs": "lang"
    },
    "props": {
      "lang": "ja",
      "layout": "TOC"
    }
  },
  {
    "params": {
      "dirs": "it"
    },
    "props": {
      "lang": "ja",
      "layout": "TOC"
    }
  },
  {
    "params": {
      "dirs": "others"
    },
    "props": {
      "lang": "ja",
      "layout": "TOC"
    }
  },
  {
    "params": {
      "dirs": "about/zh"
    },
    "props": {
      "lang": "zh",
      "layout": "TOC"
    }
  },
  {
    "params": {
      "dirs": "lang/zh"
    },
    "props": {
      "lang": "zh",
      "layout": "TOC"
    }
  },
  {
    "params": {
      "dirs": "it/zh"
    },
    "props": {
      "lang": "zh",
      "layout": "TOC"
    }
  },
  {
    "params": {
      "dirs": "others/zh"
    },
    "props": {
      "lang": "zh",
      "layout": "TOC"
    }
  },
  {
    "params": {
      "dirs": "about/en"
    },
    "props": {
      "lang": "en",
      "layout": "TOC"
    }
  },
  {
    "params": {
      "dirs": "lang/en"
    },
    "props": {
      "lang": "en",
      "layout": "TOC"
    }
  },
  {
    "params": {
      "dirs": "it/en"
    },
    "props": {
      "lang": "en",
      "layout": "TOC"
    }
  },
  {
    "params": {
      "dirs": "others/en"
    },
    "props": {
      "lang": "en",
      "layout": "TOC"
    }
  }
]
export const pagepaths: StaticPath[] = [
  {
    "params": {
      "dirs": "about",
      "path": "information"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "about",
      "path": "philosophy"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "about",
      "path": "message"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "about",
      "path": "privacy"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "about",
      "path": "recruit"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "lang",
      "path": "translation"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "lang",
      "path": "interpretation"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "lang",
      "path": "online"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "lang",
      "path": "mt"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "lang",
      "path": "works"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "ec",
      "path": "ec"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "it",
      "path": "cat"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "it",
      "path": "nlp"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "it",
      "path": "dx"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "others",
      "path": "edit"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "others",
      "path": "inbound"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "others",
      "path": "train"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "others",
      "path": "copyright"
    },
    "props": {
      "lang": "ja",
      "layout": "Base"
    }
  },
  {
    "params": {
      "dirs": "about/en",
      "path": "information"
    },
    "props": {
      "lang": "en",
      "layout": "Base"
    }
  }
]
